kind: 
name: site

steps:
- name: install
  image: blcoccaro/to-deploy:v1
  volumes:
  - name: wl
    path: /tmp/host
  commands:
  - npm -v
  - node -v
  - nodejs -v
  
volumes:
- name: wl
  host:
    path: /var/www/unique

trigger:
  branch:
  - master
  event:
  - push